### ISSUE TITLE
`atomistic` and `atomistics` coexisting?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_contrib#132]
In the `tests` folder I see `atomistics` and in the main folder there's `atomistics` inside `atomistic`. Is there particular logic in it?

**Comment by samwaseda** [comment]
To be honest I don't really understand why we have `atomistics` while all other folders are in singular.

**Comment by jan-janssen** [comment]
The name `pyiron_atomistics` is for historic reasons. Changing it is possible but it requires some work, creating the corresponding packages, fixing the import statements in all examples and so on. Therefore so far we kept `pyiron_atomistics` https://github.com/pyiron/pyiron/issues/1290

**Comment by samwaseda** [comment]
ok that's fine but then shouldn't we at least use one of those and not both?

**Comment by liamhuber** [comment]
> To be honest I don't really understand why we have `atomistics` in the first place while all other folders are in singular.

Yes, this is the problem. I'm 95% sure that when I made this folder "pyiron_atomistics" was still just "pyiron". I didn't think to go look at "pyiron/atomistics" to verify the spelling and foolishly just went with my gut and used the singular.

I'll rename it here after Easter.

> In the tests folder I see atomistics and in the main folder there's atomistics inside atomistic. Is there particular logic in it?

Anyhow, the nested behaviour will stay. The top level `atomistic(s)` will be for everything that eventually would belong in `pyiron_atomistics`, while `atomistic(s)/atomistics` is for stuff that would get migrated to `pyiron_atomistics/atomistics`. I'm not claiming the underlying system is the best, but as long as there's consistency I'm happy.
