### ISSUE TITLE
github workflow failed to update environment.yml

### ISSUE THREAD

**Issue by muh-hassani** [pyiron/pyiron_contrib#189]
In PR #187, the github workflow failed to update environment.yml file. The error message says there is nothing to commit !

**Comment by niklassiemer** [comment]
Yes, that is an open issue for packages with different names in setup.py and environment.yml (in this case pyiron-atomistics vs. pyiron_atomistics). For us this failing test  just says, do it yourself for now. I will update the work flow (hopefully soon) to have a map between these two.

**Comment by jan-janssen** [comment]
In addition I noticed that all commits are associated to @muh-hassani account, can we use @pyiron-runner instead? The token is available in the `administrative` group. We should not like one of our personal accounts to the pyiron project.

**Comment by muh-hassani** [comment]
@jan-janssen I will change this using the given token.

**Comment by muh-hassani** [comment]
I have updated the token for the dependabot workflow with the one from pyiron-runner's user account. The changes are applied to the following repos:
- pyiron_base
- pyiron_atomistics
- pyiron_contrib
- pyiron_gui
- pyiron
