### ISSUE TITLE
FEniCS dependency problems

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_contrib#38]
When paying around with the FEniCS job in #35, I get an error as soon as I try to instantiate the job. Namely, `ImportError: generic_type: type "CSGGeometry" referenced unknown base type "dolfin::Variable"`. 

This problem seems to be [known to the FEniCS community](https://fenicsproject.discourse.group/t/anaconda-installation-of-fenics-and-mshr/2062/14) since December 2019, but frankly all the solutions up to last week are still kind of crappy. 

@muh-hassani, did you run into this and how did you resolve it?

For the time being I will try rolling both fenics and mshr back to 2018 versions, which is apparently helpful.

**Comment by muh-hassani** [comment]
Yes, it is a known issue with several unworking solutions. I found the solution, provide in the link below, useful:
[https://fenicsproject.discourse.group/t/anaconda-installation-of-fenics-and-mshr/2062/14](https://fenicsproject.discourse.group/t/anaconda-installation-of-fenics-and-mshr/2062/14)
You should first search for the available version of mshr for your os, via conda search mshr -c conda-forge. Then based on the version of python you have installed, select the one with build id ending with _2. If you are using python3.8, the solution is to install: conda install -y -c conda-forge mshr=2019.1.0=py38h255090a_2

**Comment by liamhuber** [comment]
Ok thanks. What are you using to manage your conda environment? 
  I see how MartinLenz does this directly with using the command line to instantiate a new conda env, but I *really* want to avoid this because I use a unified PyCharm-managed conda env for all my pyiron development. Unfortunately, I don't see how to specify to the level of the commit hash in either PyCharm or in a regular `requirements.txt` file...

Tangentially related, how much of a headache would it be to update cmserver03 with a conda env sufficient for these FEniCS jobs?

**Comment by liamhuber** [comment]
Ok, thanks for the fast response.

I couldn't find anything about how to do this level of specification in the regular `requirements.txt`, do you have any insight here? This sort of messed up conda requirement seems to me like a very serious barrier to rolling out FEniCS capability in pyiron.

Tangentially related, is it feasible to update the cmserver03 environment to be fenics-capable in this way?

**Comment by jan-janssen** [comment]
@liamhuber you can fix specific versions in the conda `environments.yml` file that is what we also did for DAMASK at the time https://github.com/jan-janssen/pyiron-damask/blob/master/binder/environment.yml

**Comment by liamhuber** [comment]
@jan-janssen that is definitely good news, but isn't the problem still there? If I understand the git hash you provided in the DAMASK example, we then restrict users exclusively to python 3.7, or is that not how it works?

I'm cautiously optimistic that I can force things to work for my personal setup with command line conda updates, but all this installing and uninstalling is slow and all I can confirm so far is that the first hash I tried failed rigidly and is retrying flexibly. Not exactly promising...

I have to confess I really don't understand the relationship between `pyiron_package/binder/environment.yml` and what happens when someone runs `conda install pyiron_package`, which I thought relied on `setup.py`. I'm curious to learn more about this, but don't expect to know enough to fix the current issue in a general way.

**Comment by muh-hassani** [comment]
> 
> 
> Ok, thanks for the fast response.
> 
> I couldn't find anything about how to do this level of specification in the regular `requirements.txt`, do you have any insight here? This sort of messed up conda requirement seems to me like a very serious barrier to rolling out FEniCS capability in pyiron.
> 
> Tangentially related, is it feasible to update the cmserver03 environment to be fenics-capable in this way?

I will contact Ulrich, to include an image with FEniCS installed, to be used on cmserver03.

**Comment by jan-janssen** [comment]
> I have to confess I really don't understand the relationship between `pyiron_package/binder/environment.yml` and what happens when someone runs `conda install pyiron_package`, which I thought relied on `setup.py`. I'm curious to learn more about this, but don't expect to know enough to fix the current issue in a general way.

The fundamental difference between conda and pip is that conda is designed to track C, C++ and Fortran dependencies in addition to just python and that is why it was originally developed by the numpy Developers. The conda `environment.yml` is the conda equivalent of the python `requirements.txt` and we typically use the conda `environment.yml` file to fix versions of a particular software for reproducibility, for example in the melting point project we fix the version of all dependencies: 
https://github.com/pyiron/pyiron_meltingpoint/blob/master/envs/melting.yaml

Users can always create a conda environment with exactly the same software stack from such a yaml file: 
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-from-file

Regarding the issue of the `FEniCS` project I assume it is related to how they pin their dependencies or not pin. For example if software A requires library B in Version 2.0 but you now install library B in Version 3.0 this can work but commonly does not. Therefore the conda-forge team recommends leaving this pinning to the automated build process. This been said it is something the `FEniCS` developers should fix, or somebody who wants to learn more about the build process of conda packages. We had similar issues with LAMMPS and S/PHI/nX before but I was able to resolve all those - it is really not too hard.

**Comment by liamhuber** [comment]
@jan-janssen thank you for the explanation! That helps quickly clarify my mental picture.

> This been said it is something the `FEniCS` developers should fix, or somebody who wants to learn more about the build process of conda packages. We had similar issues with LAMMPS and S/PHI/nX before but I was able to resolve all those - it is really not too hard.

I 100% agree that this should be fixed up-stream. I'm actually quite frustrated with them that this issue has existed and been documented (in at least [two](https://fenicsproject.discourse.group/t/anaconda-installation-of-fenics-and-mshr/2062) [places](https://github.com/conda-forge/mshr-feedstock/issues/18)) for the timescale of a year and it's still not fixed. It invalidates their [own  instructions](https://fenics.readthedocs.io/en/latest/installation.html) of `conda install -c conda-forge fenics` and I would think it's a serious problem. 

To best preserve institutional knowledge, I think a relatively-early PhD student should learn to do this. I'll add it to the meeting agenda.

For posterity, I never managed to find the right hash to get my py2.7 environment working, so I created a fresh environment and used the MacOS-confirmed hash posted by the life-saving @MartinLenzBonn 👍 👍  in the previously linked issues threads. So far so good with the new env.

**Comment by jan-janssen** [comment]
@liamhuber To understand the error a bit more, I created a test repository - the very basic poisson example does not fail for me. Does it only fail on Mac Os X or is it a specific example which fails? Maybe you can add a pure fenics example to the repository that would help to communicate with the fenics developers https://github.com/jan-janssen/fenics-example

**Comment by liamhuber** [comment]
On my macbook the following fails:

```bash
conda install -c conda-forge fenics
python
>>> import fenics
```

^^Fails with import error. If you really, really insist I can make some sort of example, but this exact problem is already documented on [two](https://fenicsproject.discourse.group/t/anaconda-installation-of-fenics-and-mshr/2062) of [their websites](https://github.com/conda-forge/mshr-feedstock/issues/18), so I don't see a need.

The [solution](https://github.com/conda-forge/mshr-feedstock/issues/18#issuecomment-738644504) looks like this:

```bash
conda install -c conda-forge mshr=2019.1.0= py38h2af9582_2
conda install -c conda-forge fenics
python
>>> import fenics
```

^^Works. But I was originally trying with py3.7, and there you need a different git hash and I couldn't figure out which one. The git hash is also different for ubuntu (cf. same solution by MartinLenzBonn and suggestion from Muhammad above) -- i.e. this solution is annoying and machine/python version dependent.

**Comment by jan-janssen** [comment]
For python 3.7 you can try: 
```
conda install -c conda-forge mshr=2019.1.0=py37had197be_2
```

To briefly explain: 
```
<code name> = <version> = <build> 
```
And the build consists of: 
```
<python version> <git hash> _ <build number>
```

I have to admit I have a lot experience with building linux packages but less experience with building mac os X packages.

**Comment by liamhuber** [comment]
> For python 3.7 you can try:
> 
> ```
> conda install -c conda-forge mshr=2019.1.0=py37had197be_2
> ```

I'm 95% sure this is the first one I tried yesterday. It didn't work, but I think there I already had fenics installed, so maybe if you install that one cleanly it works...

Anyhow, for me it's no longer a big deal. I created a new py38 environment and simply re-built my pyiron stack. It took an annoyingly long time, but was not at all difficult.

The hash you hint should at least be useful for future readers; I see that my link to the main mshr feedstock issue got this thread tagged, so a really desperate reader can find this and try the build you suggest 😉

**Comment by jan-janssen** [comment]
@liamhuber Can you tell me which version of `fenics` you are running? 
```
conda list fenics
```

**Comment by liamhuber** [comment]
Sure thing. After adding fenics code like this:

```bash
conda install -c conda-forge mshr=2019.1.0=py38h2af9582_2
conda install -c conda-forge fenics
```

(Note that Muhammad used `conda install -y -c conda-forge mshr=2019.1.0=py38h255090a_2` for his linux environment)

I get this:

```bash
(pyiron_38) Blazejs-Air:pyiron_contrib huber$ conda list fenics
# packages in environment at /Users/huber/anaconda3/envs/pyiron_38:
#
# Name                    Version                   Build  Channel
fenics-dijitso            2019.1.0          pyhd8ed1ab_13    conda-forge
fenics-dolfin             2019.1.0         py38hb0736e2_8    conda-forge
fenics-ffc                2019.1.0          pyhd8ed1ab_13    conda-forge
fenics-fiat               2019.1.0          pyhd8ed1ab_13    conda-forge
fenics-libdolfin          2019.1.0             h765d0ea_8    conda-forge
fenics-ufl                2019.1.0          pyhd8ed1ab_13    conda-forge
```

**Comment by liamhuber** [comment]
If the environment file is order dependent, I guess putting mshr ahead does the trick. It's possible fenics is even in the mshr dependency and the fenics requirement is redundant, I haven't dug in there.

**Comment by jan-janssen** [comment]
No, there is no order dependence, the issue is the build numbers. 

When you install `fenics` first you get: 
```
fenics-dolfin =2019.1.0=*_13
```
And when you install `mesh` first you get: 
```
fenics-dolfin =2019.1.0=*_8
```
The crazy part is that you have different build numbers mixed ...

**Comment by liamhuber** [comment]
Tell me about it. I spent about a third of a day digging through issues pages and pestering Muhammad before I managed to get it running on my local machine 😝

**Comment by jan-janssen** [comment]
This should be fixed now.
