### ISSUE TITLE
pip install is broken

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_contrib#49]
This module imports directly from `pyiron_atomistics`, but odes not depend on it (only via `pyiron`).  Not sure if that's a problem with the module magic from pyiron or we should explicitly depend on it, but in any case just installing `pyiron_contrib` from pip leads to broken installation, because pyiron_atomistics is not properly pulled.

**Comment by jan-janssen** [comment]
Should be addressed in https://github.com/pyiron/pyiron_contrib/pull/45
