### ISSUE TITLE
Graphs in python

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_contrib#575]
Hi @liamhuber and @raynol-dsouza, 

When you guys created the protocols, I was wondering if you ever took a look at: 
https://networkx.org

My current thought process is that, we might want to separate the resolution of the tasks graph from its execution. The worker job I implemented is already a first step in this direction and I could see the it makes sense to have the execution separated from the resolving of the graph. 

When searching for popular frameworks for graphs, `networkx` seems to be one obvious choice, so I was wondering it that is something you or anybody else looked at. 

Best, 

Jan

**Comment by liamhuber** [comment]
Yeah, I think I did. Then, as now, when I look at the it examples I don't see any strong cases of extremely rich data being propagated along the edges, nor do they highlight execution patterns. They seem to me more focused on graph analysis, like finding shortest paths and extracting subgraphs and whatnot.

I'm absolutely on board with offloading as much of the graph operations to another library as we can though. That's the motivation for having ironflow on top of ryvencore. Py flow is the other big player that I'm aware of who goes in the direction we need.
