### ISSUE TITLE
LammpsInteractiveWithoutOutput broken

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_contrib#608]
First, I can't even instantiate it:

mwe:
```python
from pyiron_contrib import Project
pr = Project("tmp")
lmp = pr.create.job.LammpsInteractiveWithoutOutput("foo")
```

`AttributeError: 'LammpsInteractiveWithoutOutput' object has no attribute '_interactive_disable_log_file'`

<details>
  <summary>Stack trace.</summary>

  ```

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    Cell In[3], line 1
    ----> 1 lmp = pr.create.job.LammpsInteractiveWithoutOutput("foo")

    File ~/work/pyiron/pyiron_base/pyiron_base/jobs/job/jobtype.py:299, in JobFactory.__getattr__.<locals>.wrapper(job_name, delete_existing_job, delete_aborted_job)
        282 """
        283 Create one of the following jobs:
        284 - 'ExampleJob': example job just generating random number
       (...)
        296     GenericJob: job object depending on the job_type selected
        297 """
        298 job_name = _get_safe_job_name(job_name)
    --> 299 return JobType(
        300     class_name=name,
        301     project=ProjectHDFio(
        302         project=self._project.copy(), file_name=job_name
        303     ),
        304     job_name=job_name,
        305     job_class_dict=self._job_class_dict,
        306     delete_existing_job=delete_existing_job,
        307     delete_aborted_job=delete_aborted_job,
        308 )

    File ~/work/pyiron/pyiron_base/pyiron_base/jobs/job/jobtype.py:93, in JobType.__new__(cls, class_name, project, job_name, job_class_dict, delete_existing_job, delete_aborted_job)
         91 else:
         92     raise TypeError()
    ---> 93 job = job_class(project, job_name)
         94 if job.job_id is not None and not os.path.exists(job.project_hdf5.file_name):
         95     job.logger.warning(
         96         "No HDF5 file found - remove database entry and create new job! {}".format(
         97             job.job_name
         98         )
         99     )

    File ~/work/pyiron/pyiron_contrib/pyiron_contrib/nofiles/lammps.py:13, in LammpsInteractiveWithoutOutput.__init__(self, project, job_name)
         12 def __init__(self, project, job_name):
    ---> 13     super(LammpsInteractiveWithoutOutput, self).__init__(project, job_name)
         14     self._interactive_disable_log_file = False

    File ~/work/pyiron/pyiron_atomistics/pyiron_atomistics/lammps/interactive.py:39, in LammpsInteractive.__init__(self, project, job_name)
         38 def __init__(self, project, job_name):
    ---> 39     super(LammpsInteractive, self).__init__(project, job_name)
         40     self._check_opened = False
         41     self._interactive_run_command = None

    File ~/work/pyiron/pyiron_atomistics/pyiron_atomistics/lammps/base.py:80, in LammpsBase.__init__(self, project, job_name)
         79 def __init__(self, project, job_name):
    ---> 80     super(LammpsBase, self).__init__(project, job_name)
         81     self.input = Input()
         82     self._cutoff_radius = None

    File ~/work/pyiron/pyiron_atomistics/pyiron_atomistics/atomistics/job/interactive.py:28, in GenericInteractive.__init__(self, project, job_name)
         27 def __init__(self, project, job_name):
    ---> 28     super(GenericInteractive, self).__init__(project, job_name)
         29     self.output = GenericInteractiveOutput(job=self)
         30     self._structure_previous = None

    File ~/work/pyiron/pyiron_atomistics/pyiron_atomistics/atomistics/job/atomistic.py:133, in AtomisticGenericJob.__init__(self, project, job_name)
        132 def __init__(self, project, job_name):
    --> 133     super(AtomisticGenericJob, self).__init__(project, job_name)
        134     self.__version__ = "0.1"
        135     self._structure = None

    File ~/work/pyiron/pyiron_base/pyiron_base/jobs/job/interactive.py:129, in InteractiveBase.__init__(self, project, job_name)
        128 def __init__(self, project, job_name):
    --> 129     super(InteractiveBase, self).__init__(project, job_name)
        130     self._interactive_library = None
        131     self._interactive_write_input_files = False

    File ~/work/pyiron/pyiron_base/pyiron_base/jobs/job/generic.py:142, in GenericJob.__init__(self, project, job_name)
        140 if not state.database.database_is_disabled:
        141     self._status = JobStatus(db=project.db, job_id=self.job_id)
    --> 142     self.refresh_job_status()
        143 elif os.path.exists(self.project_hdf5.file_name):
        144     initial_status = read_hdf5(
        145         self.project_hdf5.file_name, self.job_name + "/status"
        146     )

    File ~/work/pyiron/pyiron_contrib/pyiron_contrib/nofiles/lammps.py:70, in LammpsInteractiveWithoutOutput.refresh_job_status(self)
         69 def refresh_job_status(self):
    ---> 70     if not self._interactive_disable_log_file:
         71         super(LammpsInteractiveWithoutOutput).refresh_job_status()

    AttributeError: 'LammpsInteractiveWithoutOutput' object has no attribute '_interactive_disable_log_file'
  ```
</details>

I fixed this by moving [`self._interactive_disable_log_file = False`](https://github.com/pyiron/pyiron_contrib/blob/653f4b62b772ff34f8b9c424247c9ec6ae7623ae/pyiron_contrib/nofiles/lammps.py#L14) _before_ the super call.
This introduced a new error, which seems to be because [the `super` call for `refresh_job_status`](https://github.com/pyiron/pyiron_contrib/blob/653f4b62b772ff34f8b9c424247c9ec6ae7623ae/pyiron_contrib/nofiles/lammps.py#L71) is too specific.
Since we only have one parent class, I just went ahead and removed the class reference from both the super calls (here's the other one).

Now I can instantiate the job just fine, but when I run it:

```python
pr = Project("tmp")
pr.remove_jobs(recursive=True, silently=True)
lmp = pr.create.job.LammpsInteractiveWithoutOutput("foo")
lmp.structure = pr.atomistics.structure.bulk('Al', cubic=True)
lmp.potential = lmp.list_potentials()[0]
lmp.calc_md(n_ionic_steps=1000, n_print=100)
with lmp.interactive_open():
    lmp.run()
```

I still get files written to HDF!

How am I supposed to use this thing? There's no docstrings and no new notebook, so I'm not even at all confident that this isn't just 95% user error...

@pmrv I think you mentioned in a meeting that you had trouble running this and had some sort of fix -- anything different from what I have here, and did you get anywhere with it?

@jan-janssen I know the development for this idea has moved over to pyiron_lammps, but there are a handful of advantages to the solution here when I'm playing around with graph stuff:
- It's super useful to have the basic static/min/md runs, but if I see right pyiron_lammps only has min (so far, obviously)
- As much as I don't want the jobs to write files etc, I don't mind leaning on the rest of the infrastructure, and in particular loading potentials is a lot more work over in pyiron_lammps
- Both the graph stuff and pyiron_lammps are under active development, and now that they're split into separate packages, I'll always be stuck using the latest _conda release_ for pyiron_lammps, or my unit tests are going to fail. This will be fine later once the package has stabilized somewhat, but leaves me frequently lagging right now

I really like the promise of what was done here, and would be most happy if we could get a simple version of this up and running.

**Comment by pmrv** [comment]
I had the same problems over in #603  I did not investigate at all why the original code is not working though.

**Comment by pmrv** [comment]
> I still get files written to HDF!

`job._interactive_disable_log_file` needs to be set as `True`.

> @pmrv I think you mentioned in a meeting that you had trouble running this and had some sort of fix -- anything different from what I have here, and did you get anywhere with it?

No, the switching around in the init is the only thing I did in #603.

**Comment by liamhuber** [comment]
> > I still get files written to HDF!
> 
> `job._interactive_disable_log_file` needs to be set as `True`.


Oh wow, derp. I did not ever read the value! In my defense `False` is a weird default for the class that is supposed to run without files, but I should still have coded with my eyes open.

Ok, I have to go get my kids so I don't have time to try again with `True` now, but I'm cautiously optimistic that will do the trick. If it does I'll make a patch PR. Thanks @pmrv!

**Comment by jan-janssen** [comment]
The `nofiles` part only works without database. Example `.pyiron` config: 
```
[DEFAULT]
RESOURCE_PATHS = /Users/janssen/pyiron/resources
PROJECT_CHECK_ENABLED = False
DISABLE_DATABASE = True
```
