### ISSUE TITLE
Some workflow classes not getting `_repr_json_` triggered

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_contrib#659]
Instead they just get the usual object class + memory location representation.

`Workflow` and `IO` somehow aren't getting their pretty JSON representation triggered, even though `Node` and `Channel` do and they all just inherit this functionality from `HasToDict`. Until I can figure out why and fix it, I added a method `json_repr()` to force this behaviour in #658.

**Comment by niklassiemer** [comment]
Did you try to call the `_repr_json_` method by hand and have a look at the outcome? If the display encounters any error it falls back to the next solution.

**Comment by liamhuber** [comment]
That sounds very plausible and I can double check, but I would also be surprised -- _repr_json_ is just returning another method I have, return self.to_dict(), and when I import JSON from IPython.display and just manually invoke JSON(self.to_dict()) it works flawlessly. (Sorry for no code formatting, I still haven't figured out how to get it working with my phone keyboard)

**Comment by liamhuber** [comment]
Closed by #805, I just missed tagging this issue at the time.
