### ISSUE TITLE
the randspg job has no warning that it fails for windows

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_contrib#670]
In the process of getting contrib switched over to using pyiron/actions, I discovered that the [RandSpg job](https://github.com/pyiron/pyiron_contrib/blob/b6a1fb33385fcb1c87e41b69477b7038ef07ff8c/pyiron_contrib/atomistics/randspg/randspg.py#L26) depends on `randspg 0.0.1` --- a package unavailable for windows.

Currently this dependency is in `.ci_support/environment.yml` but _not_ in `setup.py` or the [conda-forge feedstock dependencies](https://github.com/conda-forge/pyiron_contrib-feedstock/blob/main/recipe/meta.yaml).

In #669 I expect this to work fine since this class doesn't actually have any unit tests, so having it in the notebook env should be enough to keep the notebook tests running (which are on ubuntu-latest, so we have access to the module).

I am concerned that this job will fail in a not-clean way for Windows users.

@jan-janssen, @pmrv, both of you have made commits to this job class; does one of you want to wrap it in an import alarm or some other solution?

**Comment by pmrv** [comment]
I'll add a check.

**Comment by jan-janssen** [comment]
I created a quick test for `Randspg` on windows https://github.com/pyiron-dev/randspg-pyiron-win - everything seems to be working fine now.

**Comment by liamhuber** [comment]
> So I build the windows package for randspg https://github.com/conda-forge/randspg-feedstock/pull/4 and opened a pull request to the pyiron resources to include it https://github.com/pyiron/pyiron-resources/pull/59 .

Super! After merging #669, and once this has had a chance to be tested, I would suggest that we then upgrade the `randspg` requirement from `.ci_support/environment-notebooks.yml` to both `.ci_support/environment.yml` and `setup.py`.

> Rather than accepting that something does not work it would be good to look into the issue and try to solve it.

[*Cough*](https://github.com/pyiron/pyiron_base/issues/1073) [*cough*](https://github.com/pyiron/pyiron_base/pull/1076)

**Comment by liamhuber** [comment]
> That is a similar issue - I would prefer to fix it in https://github.com/pyiron/pyfileindex as others might have similar needs. So the file table could automatically initialize for all sub directories and then for directories which are lower in the file system hierarchy add the folders to the overall tree. That to me is the cleaner solution following the approach of separating functionality and developing useful software which is also useful outside the pyiron project.

Indeed, but none of that changes the fact that pyiron _currently_ breaks when we initialize a second `Project` with the database turned off. The changes you suggest also do not resolve the issue of two file indices being instantiated in sibling paths. So your suggested modifications to pyfileindex are absolutely good, but they are neither necessary nor sufficient to resolve the existing issue in pyiron_base.
