### ISSUE TITLE
How can I get the output in workflow?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_contrib#674]
I followed the example in the doc string:

```python
def fnc(x=0): return x + 1
n1 = Node(fnc, "x", label="n1")
wf = Workflow("my_workflow", n1)
```

While it explains myriads of ways to set inputs, it nowhere explains how to get the output, and I'm struggling to get it.

**Comment by liamhuber** [comment]
Link to docstring line? I can add some extra clarification.

You can always look at the output of the node `wf.n1.outputs.x.value`, and the workflow itself also provides shortcut access to unconnected IO on owned nodes by slapping together the node and channel names: `wf.outputs.n1_x.value`.

**Comment by samwaseda** [comment]
ah ok then I understood it correctly, and it appears it's not working, at least in my environment. `wf.n1.outputs.x.value` returns namely `None`.

**Comment by samwaseda** [comment]
> Link to docstring line?

Sorry I thought I put it above. It's [here](https://github.com/pyiron/pyiron_contrib/blob/b6a1fb33385fcb1c87e41b69477b7038ef07ff8c/pyiron_contrib/workflow/workflow.py#L87-L96)

> I can add some extra clarification.

Yeah I guess that would help
