### ISSUE TITLE
Tinybase: Basic.ipynb throwing an error

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_contrib#677]
I started playing around with `concurrent.futures` with the intent of adding a simple executor class using `ProcessPoolExecutor` to `pyiron_contrib.workflow` in order to bring it closer to `pyiron_contrib.tinybase`.

I quickly learned that `ProcessPoolExecutor` does not play nicely with the interactive interpreter (i.e. my jupyter notebook), because it needs to be able to import its tasks from `__main__` ([docs](https://docs.python.org/3/library/concurrent.futures.html#processpoolexecutor)). E.g., I have a little `scratch.py` file with the content

```python
def return_one():
    return 1
```

Then, in my notebook I get the following:

```python
def return_two():
    return 2

from scratch import return_one

from concurrent.futures import ProcessPoolExecutor

ex = ProcessPoolExecutor()
f = ex.submit(return_one)
print(f.done(), f.result()) # (True, 1)

# f = ex.submit(return_two)  # BrokenProcessPool error
```

So far so good, this is just what I expect from the docs. But, of course, I want users to be able to define new nodes in their notebook and be able to run them in the background of their workflow! So I need some sort of solution. 

This led me to look directly at `tinybase`. There is significantly more misdirection than in that simple example above, and I wondered if perhaps somehow the demo was working because the task is somehow being imported from a class defined in the (importable!) source code, and the notebook-defined functionality is being attached to that class and "appearing" as importable or something like this...

But actually, when I try to use `tinybase` instead, I get the exact same error!

```python
def return_two():
    return 2

from scratch import return_one

from pyiron_contrib.tinybase.task import FunctionTask
from pyiron_contrib.tinybase.executor import ProcessExecutor

exe = ProcessExecutor(max_processes=1).submit([FunctionTask(return_one)])
exe.run()
exe.wait()
print(exe.output[0].result)  # 1

exe = ProcessExecutor(max_processes=1).submit([FunctionTask(return_two)])
exe.run()  # BrokenProcessPool error
```

I thought maybe this was because I'm defining a function with no input, or because there was some deep and lucky magic in the notebook history that made the `ProcessExecutor` example work, so I just copied `notebooks/tinybase/Basic.ipynb` to a new working directory and ran it directly... and am getting _exactly_ the same `BrokenProcessPool` error for `ProcessExecutor` there too.

The online version of the notebook is fully executed, so it must have worked under some condition. I don't see it listed in `.ci_support/exclude`, but when I look at [the notebook tests](https://github.com/pyiron/pyiron_contrib/actions/runs/4920340443/jobs/8789023753?pr=609) I only see `notebooks/randspg.ipynb` and `notebooks/workflow_example.ipynb`, so I guess our tests aren't recursively entering the `tinybase` folder.

@pmrv, where did the successfully-executed demo come from? Can you still execute it successfully on your machine? My only hypothesis right now is that the notebook output doesn't actually correspond to the current source code, but I really _want_ it to work so I hope I'm just not being imaginative enough 🤣

**Comment by pmrv** [comment]
Weird, I ran the notebook again now just fine.  I'll take a look next week.

**Comment by jan-janssen** [comment]
> Weird, I ran the notebook again now just fine. I'll take a look next week.

Are you guys using different operation systems? https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods 
The multiprocessing package behaves different on Linux and on Mac Os and Windows. As for the later two `spawn` is used rather than `fork`. We had similar issues with https://github.com/pyiron/pylammpsmpi and https://github.com/pyiron/pympipool when we started. One way is to manually specify the method to start new sub-tasks to compare.

**Comment by liamhuber** [comment]
Nice catch, @jan-janssen -- I'm on osx and I believe Marvin is on Linux, so I bet it's working for him because he gets fork. It looks like spawn is the only one available on Windows though, so I guess we'll ultimately want a solution that works with that. I'll also keep poking at this next week.

**Comment by jan-janssen** [comment]
> did you find a workaround for this, Jan, or do you simply not provide the functionality on windows? 

I just noticed it during debugging that both behave differently and that it makes sense to check with all three different options locally. In the end I solved the issue I had with increasing memory usage by setting the `maxtasksperchild` option for the Multiprocessing pool https://github.com/pyiron/pyiron_base/blob/main/pyiron_base/jobs/worker.py#L198

**Comment by jan-janssen** [comment]
In general I have the feeling we have to be a bit careful that we do not reinvent the wheel here. As part of the IPAM workshop on "New Mathematics for the Exascale: Applications to Materials Science" https://www.ipam.ucla.edu/programs/long-programs/new-mathematics-for-the-exascale-applications-to-materials-science/  Joerg, Han and I worked a lot on scalable workflow concepts. We identified the http://flux-framework.org as a very scalable task framework at least on all linux machines which can be integrated in pyiron. The first level of integration is currently implemented on the `pysqa` level where we just use flux as an additional queuing system. But flux also offers a python interface so we are working on prototypes to use flux for all tasks which are in the 1sec and longer range. Meaning a `linspace` would still be executed locally but many other tasks would be distributed over many compute nodes. In contrast to traditional queuing systems flux has an hierarchical approach, so on the one hand it can be integrated in existing queuing system and on the other hand it can also be installed on single workstations. I tried to summarise the current state of development and the current vision for the flux usage in pyiron in https://www.youtube.com/watch?v=lXY5wOYcqxk .

**Comment by pmrv** [comment]
The execution side is not the aim of `tinybase`.  I'm happy to use flux for it.  No matter the execution platform, we'll need some form of interface that gets a list of independent tasks from the user facing code.  This is what I'm working on.  So I don't see that much problem if the pickling or so is not perfectly working on all platforms, as we can later swap this out to cloudpickle or so.

**Comment by liamhuber** [comment]
I'm also perfectly happy using a different framework, perhaps flux. For my purposes I just needed the simplest possible Executor interface for playing around with non-head-process tasks, so I think using the standard library is a good place to start.

With flux in particular, from your description, I am concerned about the Linux-only requirement, as that already rules out local development on my (and loads of people's) MacBook. But maybe I misunderstand the severity of your comment/we can get a workaround. In general I'm very content to use a third party framework for this task if we find one we like.

**Comment by jan-janssen** [comment]
> With flux in particular, from your description, I am concerned about the Linux-only requirement, as that already rules out local development on my (and loads of people's) MacBook. But maybe I misunderstand the severity of your comment/we can get a workaround. 

I see flux primarily as a solution for Linux HPC systems, on a local MacBook you presumably do not need MPI parallel executables so multiprocessing should be fine as a workaround. Things only get difficult when we want to start counting which processes are used by which MPI parallel executable. In addition flux can offer us internal queues with different priorities while the local execution would use a simple first in first out sorting for the task execution.

**Comment by liamhuber** [comment]
> I see flux primarily as a solution for Linux HPC systems, 

Yeah, that's totally fine with me. I think we should be careful to make the interface look the same regardless of which multiprocessing backend we support you're using, but that's something we ca solve during implementation.

> on a local MacBook you presumably do not need MPI parallel executables so multiprocessing should be fine as a workaround. 

Maybe I'm Not sufficiently technically informed about what you mean by MPI parallel executables, but I think we might indeed want this even for laptops? I can still see it being very useful for users to run Lammps, sphinx, etc as an multi core process in the background.

> Things only get difficult when we want to start counting which processes are used by which MPI parallel executable. 

I think I'll need to dig into the pysqa code to properly parse your meaning here. Definitely I want a solution on all systems for starting new processes (ie multiprocessing not just multi threading) -- at least for the purposes of easy local tests for how non-shared-memory paradigms are behaving. I also run into trouble before using MPI parallel executables -- like I said above, on everything but Linux, naively using concurrent.multiprocessing borks for interactive interpreters. However, I think there must be a decent workaround possible, because dask.distributed certainly gives the appearance of letting me run notebook-defined material with multiprocessing. Although again I need to dig more deeply into their source code implementation to see how they're doing this; they have their own Futures class and everything so I didn't have time to drill down to the depth I wanted or needed last week.

> In addition flux can offer us internal queues with different priorities while the local execution would use a simple first in first out sorting for the task execution.

👍👍
