### ISSUE TITLE
Workflow: Workflows and Nodes need a common ancestor

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_contrib#726]
I've been thinking about this for a while, but it was brought back to my attention in #724 where `Node` and `Workflow` both get a `Server` object attached to them independently -- these classes need a common ancestor!

I still haven't figured out exactly how to reconcile the on-the-fly adaptable nature of `Workflow` compared to a static `MacroNode` where the IO is fixed, but it's increasingly clear that we need something like `GraphElement` that holds the commonalities of `Node` and `Workflow` (such as `.server`). My current thinking is something like this: `GraphElement; HasGraph; Node(GraphElement); MacroNode(Node, HasGraph); Workflow(GraphElement, HasGraph)` and `Workflow.to_macro(self): -> MacroNode`. 

I'll take some swings at this, but I would welcome your thoughts @samwaseda!

**Comment by samwaseda** [comment]
Great! Could you maybe first explain what's fundamentally different between `Workflow`, `MacroNode` and `Node`. Especially the position of `MacroNode` is not very clear to me.

**Comment by JNmpi** [comment]
Thanks for the suggestions. I had also thought in this direction but along a slightly different solution. Rather than introducing a hierarchy of classes and subclasses, I would like to keep the class structure simple. My idea would be to address all the aspects in two main classes:

- workflow: This class has a list of nodes attached to it as well as the input and output links between the nodes.
- node: This class contains input and output arguments as well as the definition of the function call. The instance also has a reference to the workflow it is attached to. Thus, the following pseudocode applies:
`workflow = node.workflow`
`server = node.workflow.server`

- In addition, to know whether the node class is a macrocode (i.e. a workflow) it should have the following properties:
`node.is_workflow   # True or False if the node object is a macro_node (workflow) or not`
alternatively: `node.is_macronode`
The following pseudocode applies:
`node.get_node_workflow() # returns the workflow object of the macro_node (if node.is_macronode==True) otherwise None`

What I like about this concept is that only two fundamental classes are needed. Their hierarchy is directly represented via node.workflow (to get the workflow to which the node is attached) and node.get_node_workflow to get the workflow that describes the macro_node.

**Comment by liamhuber** [comment]
> workflow: This class has a list of nodes attached to it **as well as the input and output links between the nodes**.

This is how Ryven is implemented, but is actually a little different than the implementation here. Here the nodes themselves are aware of their connections! Workflows know about them only insofar as workflows know about all the nodes and can query the links easily.

> node: This class contains input and output arguments as well as the definition of the function call. 

This is where I see it productive to have `MacroNode(Node)` -- not that a `Node` _can't_ define a subgraph execution as its function call, but just that we can support this behaviour with extra tools in a subclass.

For the rest, I might say `node.parent` in case the parent is a macro node instance instead of a workflow, but the pseudocode looks overall good to me.

> ... `node.is_workflow` ... ``

Here I think we're super well aligned and just using different syntax, i.e. equivalent to my `macro_node.to_workflow()`

> What I like about this concept is that only two fundamental classes are needed. ...

I think the place I push back against here is that _most_ nodes won't have any internal graph structure -- they'll just do something -- so having `Node.get_node_workflow` right on that base `Node` class feels like overkill.

Otherwise it remains unclear to me whether we really need both `Workflow` and `MacroNode` as I suggest, or if we can get away with just `Workflow`. There I think the question comes to reusing and sharing workflows -- if _all_ we have is `Workflow` then I think reusing/sharing will only happen by copying or serializing the workflow. At the moment I still see it being very useful to have human-readable classes that can instantiate _a particular_ workflow, and that's where I see a `MacroNode` class coming in.

**Comment by JNmpi** [comment]
@liamhuber, thanks for your prompt reply. I realize that without having some (pseudo)-code examples the discussion remains a bit abstract. It would be therefore good to try to formulate a more complete example of pseudocode that describes the hierarchy of nodes, macro nodes and workflows. We should also not forget that there are tasks (created and submitted by the node to the executor) that we have not addressed so far.

As you mentioned our ideas are rather similar. A few thoughts regarding some of the issues where I am not sure that we have converged:

- Workflow as not being functional because they are running for a longer time and may have states. This applies also to nodes like VASP or Lammps that can run for long times and where the node can have 'states' such as running, aborted, finished etc. These states apply also to a workflow. In addition to these states the workflow can provide much more details, such as in which iteration step it is or which nodes are presently executed. The same may, however, apply also to VASP etc., where we could get the iteration step for electronic or atomic convergence. In this respect, I see more the difference between a fast node and a conventional node. 
- In this respect, `Node.get_node_workflow` would return None for an atomic node object, i.e. one which is not a macro node
- The different node types such as fast node, macronode etc. may be realized via templates

**Comment by liamhuber** [comment]
> I realize that without having some (pseudo)-code examples the discussion remains a bit abstract. 

Absolutely!

Here's something I'm trying to slowly code-towards for running Murnaghan. There's still stuff I don't like about it, but I hope it's helpful for the discussion.

```python
import numpy as np
from pyiron_atomistics import Atoms

from pyiron_contrib.workflow import Workflow

wf = Workflow("energy_volume")

wf.structure = wf.add.atomistics.BulkStructure(
    cubic=True, 
    element="Al"
)

# There is no node in the library for straining strucutures
# but this is easy to define
@Workflow.wrap_as.node(
    "strained",  # With Sam's idea, we won't need to write this
    # it would be automatically scraped from the name of the variable returned
    run_on_updates=True,  # We can set defaults for the new class here
    update_on_instantiation=True
    # Since they're both True we could have used fast_node instead
    # but then I couldn't demonstrate setting the defaults here ;)
)  
def strain_structure(
    structure: Atoms = Atoms(symbols="Al", pbc=True, cell=3*[4.05]), 
    strain: float = 0.
    # We need working defaults in order to run on instantiation
):
    strained = structure.copy()
    strained.apply_strain(strain)
    return strained

# Next, we want to have a macro that:
# strains a structure
# builds an engine (Lammps)
# runs a static calculation

# Let's build the macro live from a workflow:
sub_wf = Workflow("strained_static_macro")
sub_wf.strain = sub_wf.add(strain_structure())
sub_wf.engine = sub_wf.add.atomistics.Lammps(
    structure=sub_wf.outputs.strained,
)
sub_wf.calc = sub_wf.add.atomistics.CalcStatic(
    job=sub_wf.engine,
    run_on_updates=True, 
    update_on_instantiation=True
    # We know it's cheap Lammps so it's safe to always just re-run
)
loop_macro = sub_wf.to_macro(
    output_whitelist = (
        "calc_volume",  # Specify by name 
        # Remember: workflows auto-generate IO based on unconnected channels
        # -> sub_wf.outputs.calc_volume = sub_wf.calc.outputs.volume
        sub_wf.calc.outputs.energy_pot  # Or specify by object
        # Either from the wf IO or from the wf nodes themselves
        # This way we can whitelist even connected channels
        # in case we need them
    ) # ONLY the whitelisted output appears in the macro output panel
    # No input_whitelist is specified,
    # so the macro just uses all the unconnected inputs:
    # strain_structure (what we want)
    # engine_potential (available but can be ignored because default is ok)
)
# loop_macro is now a node _class_
# Its default value for run_on_updates and update_on_instantiation
# is calculated from all() of these values over its constituent nodes

# We also need to make a for-loop over this macro
# Let's nest macros by passing in the macro node from above
# into a pre-defined loop-making macro:
for_loop = Workflow.meta.for(
    loop_body = loop_macro,  # something of type Node
    iterate_on=("strain_strain",)  # strings matching loop_body input labels
    # ^^ It would be greate to do this with dot access:
    # iterate_on=loop_macro.input.strain_strain
    # But loop_macro is a _class_ and currently we only
    # build the IO on instantiation!
    # 
)
# for_loop is another node _class_
# it is hard wired to build a for-loop of nodes on instantiation
# it knows which class of node to to instantiate in that for loop
# it knows which input channels should be iterated on,
# i.e. have values distributed across the loop body instances
# and all other input is passed as-is to all loop body instances equally
# Finally, it has output with the same name as the loop body, 
# but it aggregates loop body instance output values into a list
                   
wf.loop = wf.add(
    for_loop(
        strain_structure=wf.structure, 
        # ^^Internally passed to _each_ `loop_macro` instance
        strain_strain=np.linspace(-0.05, 0.05, 5),
        # ^^Internally spread out _across_ those instances
        # Number of instances is dynamically created,
        # based on the length of iterable input at run-time
    )
)
                   
wf.plot = wf.add.standard.Scatter(
    x=wf.loop.outputs.calc_volume, 
    y=wf.loop.outputs.calc_energy_pot,
    # For loop output can be accessed as usual
)
```

Now if I look at `wf.nodes` I see `structure`, `loop`, and `plot`. 

If I look at the `wf.loop.nodes`, _after_ running I'll internally see five instances of the macro node `StrainedStaticMacro` (named after the workflow who got macro'd to make it), and maybe some extra nodes for handling the input distribution and output aggregation (e.g. the "meta node" `input_to_list` in #716 that packages a variable amount of input up as a list to output). _Before_ running, `loop` knows about its IO definition (names, types...), but not about the internals that will generate it, because the graph has variable length and thus can only be created at run-time.

If I further dig into `wf.loop.nodes["strained_static_macro_2"]` (or whatever key is needed to access nodes in the for-loop), I see `strain`, `engine`, and `calc`. I can actually look at the source code for the class in `loop_macro`, which was generated by `sub_wf.to_macro` and I should be able to see the human-readable python code that specifies how these are created and connected.

Necessary TODOs:
- Package workflows as macros
- Build a dynamic for-loop meta node
- Get access to IO labels _before_ instantiation
  - We may need to make architecture changes upstream to make this possible...

Current concerns:
- This is still pretty complex for a simple EV curve, although I do think it's pretty cool that we can nest macros in so few lines
- I'm not happy with how we interface with pyiron -- in particular it's impossible to swap out the `engine` in `StrainedStaticMacro`, because right now it's the _engine_ that takes the structure and not _calc static_! This is more a node-library problem than a real architecture problem though
- How should we handle things like dynamic for-loop meta-nodes when their input changes? E.g. what happens if we make the following update after running `wf.loop.inputs.strain_strain = np.linspace(-0.10, 0.10, 10)`? Do we delete the entire internal graph and rebuild it? I guess so...

**Comment by JNmpi** [comment]
@Liam, thanks for the pseudocode. It is super helpful to look at it and identify constructs and syntax that are (at least for me) not as intuitive as I would like to have them. Please find below some ideas with pseudocode that is at least to me easier to understand. While I still like the functional definitions of our workflow nodes I realized that when constructing workflows the underlying logic may be hard to see. I therefore feel that it would be good to have an additional alternative approach available, where the definition of the objects (nodes) and the links between them are done separately. To see the direction of the link (from input to output) I like the operator -> but we could also use >> as in airflow. I am sure that we will need a couple of iterations to come up with a solution that we all like or which is the best compromise. 

Below is the pseudocode suggestion. It provides exactly the same functionality as your example above provides:


### Imports


```python
import numpy as np
from pyiron_atomistics import Atoms

from pyiron_contrib.workflow import Workflow
```

### Define simple nodes


```python
@Workflow.wrap_as.node("strained")  
def strain_structure(structure: Atoms, strain: float = 0.):
    strained = structure.copy()
    strained.apply_strain(strain)
    return strained
```

### Define macro node from workflow


```python
sub_wf = Workflow("strained_static_macro")
sub_wf.strain = sub_wf.add.strain_structure   # define only node function (without passing arguments)
sub_wf.engine = sub_wf.add.atomistics.Lammps
sub_wf.calc = sub_wf.add.atomistics.CalcStatic

sub_wf.strain => sub_wf.engine.inputs.structure
sub_wf.engine => sub_wf.calc.inputs.job
```

#### Debug/analyse macro node


```python
sub_wf.visualize()  # similar like dask for delayed execution
```


```python
sub_wf.inputs # list all unconnected input variables, i.e. 
              # - strain.structure
              # - strain.strained
```


```python
sub_wf.outpus # list all unconnected outputs, i.e. 
              # - CalcStatic output object
```


```python
debug = Workflow("debug")
sub_wf.inputs.strain.structure = debug.create.atomistics.structure.bulk('Al', cubic=True)
sub_wf.inputs.strain.strained = 0.1

sub_wf.run()  # delayed execution, execution has to be explicitly enforced
```

### Construct workflow using the above defined nodes


```python
strained_energy = sub_wf.to_node()
# the following lines may be skipped by analyzing the workflow graph (only these outputs are connected to another node)
strained_energy.output.whitelist.add.calc.volume  # works via autocompletion
strained_energy.output.whitelist.add.calc.energy_pot
```


```python
wf = Workflow("energy_volume")

wf.structure = wf.add.atomistics.BulkStructure(
    cubic=True, 
    element="Al"
)
```


```python
wf.strained_energy = wf.add(strained_energy)
wf.strain_values = wf.add.numpy.linspace(-0.05, 0.05, 5)  # default values
wf.for_loop = wf.add.controls.for_loop
wf.plot = wf.add.standard.Scatter
```


```python
wf.strained_energy => wf.for_loop.inputs.body # maybe we need an other syntax to indicate that the entire node is connected/embedded
wf.strain_values => wf.for_loop.inputs.iterator  
wf.for_loop => wf.strained_energy.inputs.strain.strained

wf.for_loop.outputs.calc.volume => wf.plot.x
wf.for_loop.outputs.calc.energy_pot => wf.plot.y
```

#### Alternative 1: More intuitive syntax for loop


```python
wf.strained_energy = wf.add(strained_energy)
wf.plot = wf.add.standard.Scatter

with wf.for_loop(np.linspace(-0.05, 0.05, 5)) as strain:
    wf.strained_energy.inputs.strain.strained = strain  # strain iter object triggers modal execution and calls the loop object when  finished 


wf.outputs.strained_energy.calc.volume => wf.plot.x
wf.outputs.strained_energy.calc.energy_pot => wf.plot.y
```

#### Alternative 2: Parallel loop


```python
wf.strained_energy = wf.add(strained_energy)
wf.strain_values = wf.add.numpy.linspace(-0.05, 0.05, 5)  # default values
wf.plot = wf.add.standard.Scatter

wf.strain_values => wf.strained_energy.inputs.strain.strained

wf.for_loop.outputs.calc.volume => wf.plot.x
wf.for_loop.outputs.calc.energy_pot => wf.plot.y
```

#### Apply workflow


```python
wf.run()  # returns plot using default structure
```


```python
wf.inputs.structure.element = 'Fe'
wf.run()  # missing: name for this specific workflow run (like job_name)
```


```python

```

**Comment by liamhuber** [comment]
@JNmpi, thanks for the wealth of ideas!

> To see the direction of the link (from input to output) I like the operator -> but we could also use >> as in airflow.

I poked around for a `->` magic method and didn't find anything, but they definitely exist for `>>` and `=>` as used in your code. I like `foo.input.x = bar.output.y` because it's extremely pythonic and should feel familiar to most programmers. However, especially for new users without years of programming experience, I absolutely see that the feed-forward and graph-like syntax of `bar.output.y >> foo.input.x` reads nicely. It should be easy enough to support both at once, so let's just go for it!

> I therefore feel that it would be good to have an additional alternative approach available, where the definition of the objects (nodes) and the links between them are done separately.

I think this is already present, but lmk if I'm missing your meaning. E.g.:

```python
for_loop = Workflow.meta.for(
    loop_body = loop_macro,  # something of type Node
    iterate_on=("strain_strain",)  # strings matching loop_body input labels
    # ^^ It would be greate to do this with dot access:
    # iterate_on=loop_macro.input.strain_strain
    # But loop_macro is a _class_ and currently we only
    # build the IO on instantiation!
    # 
)
```

should be directly equivalent to unwrapping the creation 

```python
for_loop = Workflow.meta.for()
for_loop.loop_body = loop_macro
for_loop.interate_on=loop_macro.inputs.strain_strain
```

(Although as mentioned in the comment, we need a bit of infrastructure to get input names dot-accessible before instantiation. In principle the class has such information available for us to make the necessary maps, we just don't format and expose it this way.)

and 

```python
sub_wf.engine = sub_wf.add.atomistics.Lammps(
    structure=sub_wf.outputs.strained,
)
```

(with the planned magic method syntax) is equivalent to

```python
sub_wf.engine = sub_wf.add.atomistics.Lammps()
sub_wf.outputs.strained >> sub_wf.engine. structure
```

> It is super helpful to look at it and identify constructs and syntax that are (at least for me) not as intuitive as I would like to have them. Please find below some ideas with pseudocode that is at least to me easier to understand. 

Here I'm afraid I've got quite a bit of misunderstanding, most of which stems from intermixing node instances and node classes. E.g. here (and elsewhere) a class is added to the `Workflow.nodes` collection:

`sub_wf.strain = sub_wf.add.strain_structure   # define only node function (without passing arguments)`

What does it mean for a workflow to be assigned a node _class_ instead of a node _instance_? What happens when I attempt to run such a workflow? What does it mean for future node instances if I've made an assignment (value or connection) to the input of that node's _class_ living on a workflow? By the time I get to the for-loop syntax examples, there's enough of a mixture of instances and classes that I'm not sure how to interpret the intended interface.

**Comment by liamhuber** [comment]
As of #749, `Workflow(Composite(Node))` and `Function(Node)` do now share the same root `Node` ancestor.
