### ISSUE TITLE
Workflow: Why can't `Node` have a `working_directory`

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_contrib#744]
without a parent `Workflow`? 

I can imagine that you make a workflow with some label, run it, and populate a folder. We then don't want to instantiate another workflow or another node with the same label at that level, lest their working directories conflict. Instead of forbidding nodes from having their own working directories, could we instead check for populated working directories at either instantiation or serialization time and raise an error then if the label is already in use?

**Comment by samwaseda** [comment]
I'm sort of ok with that, but I don't want to have so many folders lying around. Maybe we can think about creating a main folder first?

**Comment by liamhuber** [comment]
I merged #745 after addressing your comments so I could keep moving, but I recognize this issue is still open and we'll need to do more work to avoid having directories all over the place.

**Comment by samwaseda** [comment]
> I thought that this cleanliness was basically the point of requiring the nodes to have a workflow before allowing working directories to start with...

Yeah exactly, so now I'm a bit confused because I don't really understand why the nodes should be allowed to have a folder without workflows...

> Would there really be so many folders?

No idea, but compared to one folder created by the workflow, it probably will be more

Maybe we should have something like a main folder (e.g. simply `pyiron`) if someone who doesn't have a parent tries to create a folder.

> Basically just introduce a speed-bump so we only get new folders when we really want them.

There, I might prefer to allow users to create folders easily. It might be good to add a functionality in pyiron to clean up empty folders afterwards though. Basically we could add `__del__` in `Node` (now called `Function`?) where pyiron checks whether `self._working_directory` is `None`, and if not, whether the folder has anything inside.

**Comment by liamhuber** [comment]
> Yeah exactly, so now I'm a bit confused because I don't really understand why the nodes should be allowed to have a folder without workflows...

The more I think about it, the more it is actually quite harsh to not allow nodes a folder without belonging to a parent. In principle, we allow nodes (e.g. `Function` nodes) to exist and be executed as stand-alone objects. And the `working_directory` exists in case node execution requires a place to write files to. So....file writing nodes are simply not allowed to execute outside a workflow? This isn't, like, a catastrophe, but it seems to me to be an unnecessary exception to the rule, and potentially annoying when developing and debugging a new node that needs to write something.

In conclusion, I'd like nodes to be able to make a working directory even if they don't have a parent.

> Maybe we should have something like a main folder (e.g. simply `pyiron`) if someone who doesn't have a parent tries to create a folder.

This still feels like just a trivial can-kick. If the user doesn't want to populate the cwd with node directories, just cd before starting to use the nodes?

> Basically we could add `__del__` in `Node` (now called `Function`?) where pyiron checks whether `self._working_directory is None`, and if not, whether the folder has anything inside.

I really like this! I would say `Node.__del__` checks if the working directory exists and is empty, and if so it deletes it; the `Composite.__del__` starts by invoking the same cleanup routine on its children, then supers to clean itself. This way we will recursively clean up directories on every empty branch of the tree that it can.

I guess `__del__` gets skipped in the case of a hard crash of the python interpreter -- like if I unplug my desktop computer or w/e -- but this is just convenient housekeeping so I suppose it doesn't need to be 110% robust.

**Comment by liamhuber** [comment]
Closing with the conclusion that nodes _can_ have a working directory. In fact, we currently put it on the root-most `Node` class.
