### ISSUE TITLE
meta discussion: sub-module tags?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_contrib#747]
I think it was @pmrv who started naming stuff "Tinybase: ..." or maybe @samwaseda with "Workflow: ...", but either way --- I like it.

Instead of eating up a bunch of name space each time, what do you think about introducing new GitHub labels for each of the eight `pyiron_contrib` sub-modules? These could be added/removed as sub-modules come into existence/are removed if their code gets "promoted" into one of the more stable repos.

**Comment by samwaseda** [comment]
Sure. I just sort of stopped using labels when Jan started moving around repositories some years ago and the old labels got lost. But now since the repositories are again more or less stable, so we can think about properly defining them again.
