### ISSUE TITLE
Moving atomicrex to pyiron_gpl

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_contrib#91]
@Leimeroth I just realised the atomicrex is published under GPL rather than LGPL as I imagined. As a consequence it might be reasonable to move it to `pyiron_gpl`. For the up coming potential workshop this would also have the advantage that we only depend on `pyiron_atomistics` and `pyiron_gpl`.

**Comment by Leimeroth** [comment]
I am fine with that.

**Comment by pmrv** [comment]
> @Leimeroth I just realised the atomicrex is published under GPL rather than LGPL as I imagined. As a consequence it might be reasonable to move it to `pyiron_gpl`. For the up coming potential workshop this would also have the advantage that we only depend on `pyiron_atomistics` and `pyiron_gpl`.

We still need the TrainingContainer from `pyiron_contrib`, however.

**Comment by jan-janssen** [comment]
> We still need the TrainingContainer from `pyiron_contrib`, however.

Or we migrate those to `pyiron_atomistics` - I guess both is fine. We just have to be a bit careful with the licenses.

**Comment by jan-janssen** [comment]
Ok, I looked at the licensing again and realised that the atomicrex wrapper is not using the atomicrex python classes but instead directly calls the atomicrex executable. In this case it is fine to license the code under the BSD license which is our preferred option and keep it in `pyiron_contrib` before moving it to `pyiron_atomistics`. 

https://www.gnu.org/licenses/gpl-faq.html
> Where's the line between two separate programs, and one program with two parts? This is a legal question, which ultimately judges will decide. We believe that a proper criterion depends both on the mechanism of communication (exec, pipes, rpc, function calls within a shared address space, etc.) and the semantics of the communication (what kinds of information are interchanged).
> 
> If the modules are included in the same executable file, they are definitely combined in one program. If modules are designed to run linked together in a shared address space, that almost surely means combining them into one program.
> 
> By contrast, pipes, sockets and command-line arguments are communication mechanisms normally used between two separate programs.

**Comment by Leimeroth** [comment]
I guess this is still good to know if I try to extend the interface with an interactive version.

**Comment by pmrv** [comment]
> > We still need the TrainingContainer from `pyiron_contrib`, however.
> 
> Or we migrate those to `pyiron_atomistics` - I guess both is fine. We just have to be a bit careful with the licenses.

Not at all opposed to having the `TrainingContainer` in `pyiron_atomistics`, but since pyiron imports the other modules automatically I would say we save the busy work until after the work as it doesn't impact the participants at all.
